stages:
- prepare
- build
- test

variables:
  REGISTRY: "quay.io"
  CONTAINER_IMAGE: travelping/upf
  # this points to buildkitd k8s service
  BUILDKITD_ADDR: tcp://buildkitd:1234
  # This is needed to disable TLS in recent docker:...dind images.
  # TLS there is not really needed as docker client connects
  # to localhost, and all of the docker certs only cause problems
  # here
  DOCKER_TLS_CERTDIR: ""

# prepare build image
prepare:
  stage: prepare
  # image: moby/buildkit:v0.7.1@sha256:530396a0ef93eacc025dadeb6a8a69d8c87ca402f48df9bc7c8c767b46fe9cf3
  image: docker:git
  services:
  - docker:19.03.8-dind
  script:
  - export DOCKER_HOST="tcp://localhost:2375"
  - echo "quay.io login..."
  - docker login -u ${QUAY_USER_ID} -p ${QUAY_TOKEN} ${REGISTRY}
  - echo "Ensuring that proper build image exists ..."
  - PUSH_BUILD_IMAGE=1 sh extras/docker/ensure-build-image.sh
  # FIXME: push from buildkit to quay.io fails with '401 UNAUTHORIZED'
  # for some reason, and it only happens with build images
  # - echo "registry login..."
  # # 'docker' command not available in the buildkit image
  # - >
  #   REGISTRY_LOGIN=${QUAY_USER_ID}
  #   REGISTRY_PASSWORD=${QUAY_TOKEN}
  #   extras/docker/registry-login.sh "${REGISTRY}"
  # - echo "Ensuring that proper build image exists ..."
  # - USE_BUILDCTL=1 PUSH_BUILD_IMAGE=1 sh extras/docker/ensure-build-image.sh
  only:
    changes:
    - .gitlab-ci.yml
    - Makefile
    - extras/docker/Dockerfile.build
    - build/external/**/*

# build container image
.build:
  stage: build
  image: quay.io/travelping/upf-build:26f11d1fa17a9a506f651ab4a34bf317 # XX_DO_NOT_REMOVE_THIS_COMMENT
  script:
  - >
    REGISTRY_LOGIN=${QUAY_USER_ID}
    REGISTRY_PASSWORD=${QUAY_TOKEN}
    extras/docker/ci-build.sh
  - mv /tmp/_out "${CI_BUILD_NAME##*:}"
  dependencies:
  - prepare

# build container image
build:release:
  extends: .build
  variables:
    DOCKERFILE: Dockerfile
  artifacts:
    when: always
    untracked: true
    paths:
    - release/debs
    - release/testfiles.tar.gz

build:debug:
  extends: .build
  variables:
    DOCKERFILE: Dockerfile.devel
  artifacts:
    when: always
    untracked: true
    paths:
    - debug/debs
    - debug/testfiles.tar.gz
