stages:
- build

variables:
  # This is needed to disable TLS in recent docker:dind images.
  # TLS there is not really needed as docker client connects
  # to localhost, and all of the docker certs only cause problems
  # here
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  #tags:
  #  - docker
  image: docker:git
  services:
  - docker:19.03.8-dind
  script:
  - docker run --rm busybox ip a
  - sleep 1000
